### PR TITLE
Moves content guide to USWDS template

### LINKED ISSUE #234: switch to uswds-jekyll
This guide is still using the `guides_style_18f` theme, which is deprecated, and isn't compatible with newer versions of Jekyll.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #234 #232 #219 

[✍️ PREVIEW](https://federalist-de5c0cb8-65b2-45b8-bcc6-6fd137e9b755.app.cloud.gov/preview/18f/content-guide/uswds-port/)

- Moves existing content guide markdown files into `uswds-jekyll` template based on UX Guide
- Fixes broken links
- Fixes dependency issues with current guide
- Brings guide up to date with other 18F guides
- Creates redirects for existing page paths to new page paths

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
Here's a trick I learned just this week – you can change the default layout in _config.yml. This gets around having to add `layout: post` to all the pages:
https://github.com/18F/isildurs-bane/commit/ce794daeac9e512fcc3e44759612584fbad4d0fc

Some other minor stuff that you might want to replicate here that I resolved in the 18F/isildurs-bane after stealing all the good stuff from ux-guide, et al:

Fix to get the Slack icon working in Federalist previews:
https://github.com/18F/isildurs-bane/commit/b9f7b77b595a9b68395ea2fa16c7942824518a41#diff-8314c3828f04eb59524bcefea6346e5b

Syntax error in footer.html:
https://github.com/18F/isildurs-bane/commit/8b0257d83abc928be74960ac378a99c86855fe53

Most of the other things I did to the code that originated in ux-guide was to generalize it in minor ways; e.g., fixes to support guides that weren't managed by 18F and to and to incorporate all the scaffolding around the guide that we we use in the TTS handbook, Before you ship guide, etc.

**Comment by brentryanjohnson** [comment]
Thank you, @ryanhofdotgov. I think I've fixed the items you noted. The images in this repo are in a different location than those in (the wonderfully named) `isildurs-bane`. I assume I simply need to back the path out in the same way, despite it being in a different path.

Could you review the changes, if and when you have a chance?

**Review by ryanhofdotgov — APPROVED** [review]
LGTM

**Comment by ryanhofdotgov** [comment]
If you want to add Docker support and CircleCI linking checking in another pass, I can help you do that some time.

**Pull request merged**
