### PR TITLE
55 names on second reference

### PR DESCRIPTION
**Pull request by tadhg-ohiggins**

### CODE REVIEW

**Comment by nicoleslaw** [comment]
Before I had seen your PR, I suggested something like this on our call today:

- create a new section under `our-style` called `names`
- rename `states` to `state names` and move it there
- add this `personal names` entry there too

This would give us room to grow for project names, company names, agency names, etc. What do you think?

If you agree, want me to do that on this branch, or merge this and then open a new issue?

**Comment by tadhg-ohiggins** [comment]
@nicoleslaw That all sounds good to me; this PR was mainly to get the content into the guide in some form.

My vote would be to keep the same issue and to use this branch and PR, and update the branch to make the changes you suggest.

**Comment by nicoleslaw** [comment]
@coreycaitlin I think this is ready for your review. I noticed that the branch didn't have the `forms` and `keep-refining` content, but I think I fixed the merge conflict.

**Comment by coreycaitlin** [comment]
This looks good! Merging.

**Pull request merged**
