### PR TITLE
Update avoid-duplication.md

### PR DESCRIPTION
**Pull request by michelle-rago**
If we're going to include BIng we can add DuckDuckGo (which has about half of Bing's market share, but less than Yahoo's). I also added USA.gov.

### CODE REVIEW

**Comment by durland18F** [comment]
If it were the Jeff Content Guide, we would also remove Bing. But since it isn't, this seems like the right change.

**Review by durland18F — APPROVED** [review]

**Comment by ryanhofdotgov** [comment]
Since DuckDuckGo just uses Bing under the hood, FWIW I think the core issue is really the [the filter bubble](https://en.wikipedia.org/wiki/Filter_bubble) that is created by the personalized search algorithms that Google and Bing use. DuckDuckGo de-personalizes searches; [it's harder to disable that in Google, but seems possible](https://www.makeuseof.com/google-unfiltered-search-results/) – and they keep making it more difficult.

Other things to try and avoid the filter bubble and potentially see what other users might see – use incognito browser windows that aren't signed into Google, perform the search from a different region (e.g., connect to west/central/east coast GSA VPNs).

**Review by brentryanjohnson — APPROVED** [review]

**Comment by michelle-rago** [comment]
That is useful info, @ryanhofdotgov. One reason I added Duck was to avoid the appearance of bias (which we need to consider when listing or linking to commercial services).

**Comment by ryanhofdotgov** [comment]
Ah – of course! 👍

**Pull request merged**
