### PR TITLE
Remove Docker instructions

### PR DESCRIPTION
**Pull request by awfrancisco**
cc @coreycaitlin

### CODE REVIEW

**Review by wslack — APPROVED** [review]

**Comment by hbillings** [comment]
Why remove this? It's a much easier way to run the site than having to make sure all the dependencies are up to date (also, I just installed the project and these instructions work perfectly).

If we _are_ going to remove it, we should also remove the corresponding Docker functionality from the codebase, otherwise it will be confusing to folks downloading the repo for the first time.

**Review by coreycaitlin — APPROVED** [review]
👍

**Comment by coreycaitlin** [comment]
@hbillings Sorry, Heather — I merged before seeing your comment! We're removing because it doesn't work consistently (see #217), and we don't have folks in #g-content who can fix it so it does. Would you be game to pair on removing the corresponding functionality?

**Comment by tbaxter-18f** [comment]
The link back to #217 and the extra context that it hasn't worked reliably on Windows or Mac is all I was looking for. Thanks for adding that @coreycaitlin. It did make me have to erase the big note I was in the middle of writing asking for that extra context :-)

**Comment by hbillings** [comment]
I see... those issues seem more localized to individual computers (permissions and OS) than indicative of the functionality itself being broken. Also, since I'm actively working on the site's development, I'm going to keep my docker setup, because otherwise it's difficult for me to sandbox from other projects, heh.

**Comment by coreycaitlin** [comment]
@hbillings That makes sense! If you're game to help fix it/document better, I would be **super** happy to pair on it. My prior experience trying to troubleshoot Docker setups so they'd work consistently led me to believe it might not be a trivial ask to get this working again. @awfrancisco put out a call for help a while ago, and we didn't have any luck, so we decided to remove the instructions.

**Pull request merged**
