### PR TITLE
Removing link to a book

### PR DESCRIPTION
**Pull request by awfrancisco**

### CODE REVIEW

**Comment by wslack** [comment]
@awfrancisco can we change to a link like https://medium.com/the-ux-book-club/review-of-youre-my-favorite-client-b649c5c599d2 or https://hookagency.com/youre-my-favorite-client-book-review/

**Comment by awfrancisco** [comment]
No, neither of those links are appropriate. The subhead for the first one still falls into the endorsement category and the main video on the second one does not have an appropriate title.

**Comment by wslack** [comment]
How about https://kottke.org/14/10/youre-my-favorite-client or https://sketchfolio.com/you-are-my-favorite-client/

**Comment by awfrancisco** [comment]
We can link to free resources, and a book is not a free resource. Those links could also be seen as us endorsing the book.

**Comment by wslack** [comment]
Cool. (Also, I'm not sure who owns this repo but would suggest they merge. Maybe @kategarklavs knows?)

**Comment by awfrancisco** [comment]
The guild owns it. @coreycaitlin or @kategarklavs can you review?

**Pull request merged**
