### PR TITLE
Put voice and tone sentences in a block quote

### PR DESCRIPTION
**Pull request by toolness**
There's a few example sentences in the voice and tone section of the guide that are formatted the same way as the surrounding text, which can potentially confuse readers:

> screen shot 2016-10-18 at 9 49 30 am

This PR puts them in blockquote. It also puts quotes around the word "federal", which might help readability too:

> screen shot 2016-10-18 at 9 50 23 am

Hmm, I just realized that I'm not sure if the comma after "federal" should be inside the quotes or not. Let me know if they need to be and I'll fix it--or we can use an alternative styling instead of quotes...

### CODE REVIEW

**Comment by kategarklavs** [comment]
Hey @toolness — thanks for catching this and putting the selected text in block quotes 👍  (Also, per your question, the comma should be inside the quotation marks — if you would update this, I'd be much obliged!)

**Comment by toolness** [comment]
Sure thing! Just fixed the comma.

**Comment by kategarklavs** [comment]
@toolness Many thanks(!)

**Comment by tadhg-ohiggins** [comment]
I have a couple of minor changes that would make it look like this, what do people think?

image

**Comment by toolness** [comment]
Hmm, so while the whole "render emphasized text within italics as un-italicized" thing is typographically correct, to be honest it's always caused me to do a double-take and some extra mental processing to figure out what's actually being emphasized--it's kind of like the typographic analogue of a double negative to me, I guess.

So I prefer either keeping _federal_ in quotes as-is, or doing what you suggested in Slack and simply un-italicizing block quotes--which is fine typographically since blockquotes already have the left-border and the indent--and then italicizing _federal_. Just my 2 cents though!

**Comment by tadhg-ohiggins** [comment]
I'm inclined to agree; here's my next suggestion (no italics, 2em left padding on the paragraph):

image

**Comment by tadhg-ohiggins** [comment]
Here's a version with 1em padding in case the prior one is a little too much:

image

**Comment by toolness** [comment]
Nice, I like it!  The 1em padding looks best to me but the 2em is fine too.

**Comment by tadhg-ohiggins** [comment]
I modified this branch to remove the italicization on blockquotes and instead indent by 1em.

This is what it looks like:
image

**Pull request merged**
