### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by emileighoutlaw**
Makes sections alphabetical order

cc @mbland

### CODE REVIEW

**Comment by kategarklavs** [comment]
Question: Will the Intro remain the first section/References remain the last?

**Comment by awfrancisco** [comment]
Looks like yes. It's manual, not automatic. Which leads me to ask, should References be out of order and at the bottom?

**Comment by kategarklavs** [comment]
I like the idea of keeping References at the end (use the form of the guide to inform usage — references appear at the end to encourage further study). Thoughts?

**Comment by emileighoutlaw** [comment]
Oh yes. I'll fix that as soon as I get out of this meeting. :)

**Comment by kategarklavs** [comment]
@emileighoutlaw Sounds good!

**Comment by emileighoutlaw** [comment]
Should be good now!

cc @kategarklavs @awfrancisco

**Pull request merged**
