### PR TITLE
Continuous Integration/Tests setup

### PR DESCRIPTION
**Pull request by tadhg-ohiggins**
Add HTML Proofer, a `ci_build` command for `go`, and a `.travis.yml` file that calls `go ci_build` for a Travis Continuous Integration test.

All of which adds up to each PR running a set of basic checks and then GitHub displaying a pass/fail for that PR, so if we break links in a commit, it'll warn us of that. Running `go ci_build` locally will run the same tests, so it should be easy to see locally whether or not we've broken something.

### CODE REVIEW

**Comment by tadhg-ohiggins** [comment]
I added the `do not merge` label because I thought we might want to talk this PR over in the guild channel.

**Comment by toolness** [comment]
Hmm, I'm unfamiliar with [HTML Proofer](https://github.com/gjtorikian/html-proofer), and am generally fairly novice when it comes to Ruby, so I don't feel particularly qualified to review the actual code of this PR, but I definitely like the idea a lot.  I think all our static sites should incorporate something like this!

**Comment by nicoleslaw** [comment]
Same comment from me—I like the idea but am not qualified to review this. Is it worth asking someone in #ruby to take a look?

**Comment by tadhg-ohiggins** [comment]
I'm asking in #jekyll, we'll see if that yields a response.

**Pull request merged**
